apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: reuser
build:
  artifacts:
  - image: reuser
    docker:
      dockerfile: Dockerfile
      target: dev
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
      - src: 'src/**/*.tsx'
        dest: .
      - src: 'src/**/*.css'
        dest: .
      - src: 'public/**/*'
        dest: .
manifests:
  rawYaml:
  - k8s/*.yaml
portForward:
- resourceType: service
  resourceName: reuser
  port: 3000
  localPort: 3000
